
image: node:14.16.0

pages:
  stage: deploy
  before_script:
    - git submodule sync --recursive && git submodule update --remote --init
    - npm install
    - node Test.js
  script:
    - chmod +x ./Build.sh
    - ./Build.sh
    - mkdir .public
    - cp -a dist/. .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
