variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: node:14.16.0

pages:
  stage: deploy
  before_script:
    - git submodule status
    - npm install
    - node -v
    - node Test.js
  script:
    - chmod +x ./Build.sh
    - ./Build.sh
    - mkdir .public
    - cp -r dist .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
