# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    
  script:
    - rm -f Content/m-style.css
    - cp -f project-help/from/style-test-mobile.css Content
    - webpack
    - mkdir .public
    - cp -r * .public
    - mv .public public        
  artifacts:
    paths:
      - public
  only:
    - master
