FROM node:14-alpine

pages:
  stage: deploy
  before_script:
    - git submodule status
    - git submodule sync --recursive
    - git submodule update --remote --init --recursive
    - git submodule status
    - npm install
    - node -v
    - node Test.js
  script:
    - chmod +x ./Build.sh
    - ./Build.sh
  artifacts:
    paths:
      - public
  only:
    - master
