
image: node:14.16.0
CACHE_PATH: "C:/gitlab-runner/cache/group/project/repo/"

cleanup_job:
  stage: cleanup
  script:
    - echo "Cleaning up"
    - rm -rf "%CACHE_PATH%/%CI_PIPELINE_ID%"
  when: always
pages:
  stage: deploy
  before_script:
    - git submodule sync --recursive && git submodule update --remote --init
    - npm install
    - node Test.js
  script:
    - chmod +x ./Build.sh
    - ./Build.sh
    - cd project-help
    - node buildAssets.js
    - cd ..
    - chmod +x ./afterBuild.sh
    - ./afterBuild.sh
  artifacts:
    paths:
      - public
  only:
    - master

    