
image: node:14.16.0

stages:
  - cleanup
  - pages

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up"
    - rm -rf "C:/gitlab-runner/cache/group/project/repo/%CI_PIPELINE_ID%"
  when: always

pages:
  stage: pages
  before_script:
    - git submodule sync --recursive && git submodule update --remote --init
    - npm install
    - node Test.js
  script:
    - chmod +x ./Build.sh
    - ./Build.sh
    - cd project-help
    - node buildAssets.js
    - cd ..
    - chmod +x ./afterBuild.sh
    - ./afterBuild.sh
  artifacts:
    paths:
      - public
  only:
    - master

    