
image: node:14.16.0

pages:
  stage: deploy
  before_script:
    - git submodule sync --recursive && git submodule update --remote --init
    - git submodule status
    - npm install
    - node Test.js
  script:
    - chmod +x ./Build.sh
    - ./Build.sh
    - mkdir .public
    - cp -a dist/. .public
    - mkdir .public/Content
    - mkdir .public/Content/css
    - cp -f src/testAdditional.js .public/Content
    - cp -f project-help/from/style-test-mobile.css .public/Content/css
    - cp -f project-help/from/jquery.min.js .public/Content
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
