
image: node:latest

pages:
  stage: deploy
  before_script:
    - git submodule add git@gitlab.com:ramzelkin/project-help.git
    - cat .gitmodules
        [submodule "project-help"]
        path = project-help
        url = https://gitlab.com/ramzelkin/project-help
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - npm install
  script:
    - rm -rf Content/fonts
    - rm -f Content/css/style-test-mobile.css
    - cp -R -f project-help/from/fonts Content
    - cp -f project-help/from/style-test-mobile.css Content/css
    - npm run pages-build
    - mkdir .public
    - cp -r * .public
    - mv .public public   
  artifacts:
    paths:
      - public
  only:
    - master
