# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:latest
        
stages:
    - pages

# publish:
#     stage: publish
#     image: node:12.0-slim
#     script:
#         - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
#         - npm publish
#     only:
#         - master
pages:
  stage: pages
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - rm -f --verbose Content/m-style.css
    - cp -f --verbose project-help/from/style-test-mobile.css Content
    - rm -f -r --verbose Content/fonts
    - cp -f -R --verbose project-help/from/fonts Content
    - npm install
    - npm run build
    - mkdir .public
    - cp -r * .public
    - mv .public public        
  artifacts:
    paths:
      - public
  only:
    - master
