 trigger_build:
  stage: deploy
  script:
    - apk --no-cache add curl
    - "curl -X POST -F token=TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/21167966/trigger/pipeline"
    
image: node:latest

pages:
  stage: deploy
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - npm install
  script:
    - rm -rf Content/fonts
    - rm -f Content/css/style-test-mobile.css
    - cp -R -f project-help/from/fonts Content
    - cp -f project-help/from/style-test-mobile.css Content/css
    - npm run pages-build
    - mkdir .public
    - cp -r * .public
    - mv .public public   
  artifacts:
    paths:
      - public
  only:
    - master
