
image: node:14.16.0

variables:
  sha: CI_COMMIT_SHA

pages:
  stage: deploy
  cache:
    key: sha
  before_script:
    - git submodule sync --recursive && git submodule update --remote --init
    - git submodule status
    - npm install
    - node Test.js
  script:
    - export
    - chmod +x ./Build.sh
    - ./Build.sh
    - cd project-help
    - node buildAssets.js
    - cd ..
    - chmod +x ./afterBuild.sh
    - ./afterBuild.sh
  artifacts:
    paths:
      - public
  only:
    - master
