# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
# image: node:latest
# 
# stages:
#     - deploy

# publish:
#     stage: publish
#     image: node:12.0-slim
#     script:
#         - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
#         - npm publish
#     only:
#         - master
pages:
  stage: deploy
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ls Content
    - rm -rf Content/fonts
    - ls Content
    - rm -f Content/style-test-mobile.css
    - ls Content
  script:
    - mkdir .public
    - cp -r * .public
    - ls -lah .public/
    - ls -lah .public/Content 
    - mv .public public   
    - ls -lah public/Content     
  artifacts:
    paths:
      - public
  only:
    - master
